platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }
inputs:
  - name: bosh-cpi-src
  - name: version-semver
outputs:
  - name: dev-artifacts
run:
  path: bosh-cpi-src/ci/tasks/build-candidate.sh
