jobs:
  - name: pyvmomi_to_ruby-tests
    plan:
      - get: bosh-cpi-src
        trigger: true
      - task: test
        file: bosh-cpi-src/ci/tasks/test-pyvmomi_to_ruby.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - get: bosh-cpi-src
          trigger: true
        - get: version-semver
          trigger: false
          params:
            bump: patch
      - put: version-semver
        params:
          file: version-semver/number
      - task: build
        file: bosh-cpi-src/ci/tasks/build-candidate.yml
      - put: bosh-cpi-artifacts
        params:
          file: 'dev-artifacts/*.tgz'

  - name: lifecycle-6.5
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src}
        - get: stemcell
        - {trigger: true,                             get: vcpi-nimbus}
      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS: "--tag ~nsx_vsphere --tag ~nsx_transformers --tag ~disk_migration"
          DBCUSER: {{dbc_user}}
          DBCHOST: {{dbc_host}}
          DBC_SSH_KEY: {{dbc_key}}

  - name: lifecycle-6.0
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src}
        - get: stemcell
        - {trigger: true,                             get: vcpi-nimbus}
      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS: "--tag ~nsx_vsphere --tag ~nsx_transformers"
          DBCUSER: {{dbc_user}}
          DBCHOST: {{dbc_host}}
          DBC_SSH_KEY: {{dbc_key}}
          VCBUILD: ob-7037817
          ESXBUILD: '5367062'

  - name: lifecycle-6.5-nsx-t
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src}
        - get: stemcell
        - {trigger: true,                             get: vcpi-nimbus}
      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS: "--tag nsx_transformers"
          DBCUSER: {{dbc_user}}
          DBCHOST: {{dbc_host}}
          DBC_SSH_KEY: {{dbc_key}}
          TEST_NSX: "true"
          NSXT_SKIP_SSL_VERIFY: "true"

resources:
  - name: bosh-cpi-artifacts
    type: s3
    source:
      regexp:            bosh-vsphere-cpi-([\d\.]+)\.tgz
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}
  - name: vcpi-nimbus
    type: git
    source:
      uri:         git@gitlab.eng.vmware.com:PKS/vcpi-nimbus.git
      branch:      ci-master
      private_key: {{vcpi-nimbus_deployment_key}}
  - name: bosh-cpi-src
    type: git
    source:
      uri:         git@github.com:cloudfoundry-incubator/bosh-vsphere-cpi-release.git
      branch:      vmware-ci
      private_key: {{github_deployment_key__bosh-vsphere-cpi-release}}
  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
